### ISSUE TITLE
Tracking lost when running/rotating quickly

### ISSUE THREAD

**Issue by burtonrider** [google-ar/arcore-unity-sdk#101]
Hello,

We've been experiencing loss of tracking as we run/rotate in a field. The tracking is usually lost when we rotate quickly (i.e., while holding the phone in front of you, do a quick 360° turn around yourself) or running which happens a lot in our game. This in turn causes the Anchors to be lost and we lose the game objects. We've been looking for a workaround (like https://github.com/google-ar/arcore-unity-sdk/issues/37) but unfortunately it requires the user to recalibrate their field which doesn't really work in a time based game.

We've been testing using Google Pixel (1). You should be able to reproduce this using the sample game(HelloAR) which comes with the ARCore Unity package. The steps would be as follows:

1. Detect surface
2. Place bunch of mini droids
3. Run away from them in opposite direction and do a quick 180° turn
4. See if droids are still there

Is there something we can do to fix this? Can we expect this to improve with future updates?

Thanks!

**Comment by chaosemer** [comment]
This is a limitation of visual-inertial tracking. Quick motions will make the image used for tracking too blurry to be used (removing the usability of visuals) and saturate the IMU (removing the usability of inertia).

While I expect this tech will improve as time goes on, there will also be motion that is beyond our capabilities to track. Don't expect quick 360° turns to work for a while.

Closing as this is a fundamental limitation of visual-inertial tracking.

**Comment by ChristophGeske** [comment]
What would happen if you allow for higher camera frame rates? Shouldn't that allow for accurate feature detection even at fast movements. Using the slow motion camera mode (240fps) on my Samsung S7 resulted in a smooth picture even at fast movements. 
Regarding the IMU all the daydream ready phones come with a low latency IMU and they can track my head movements perfectly even if I move quickly.
I understand that older phones which are not daydream ready reach thair hardware limits for the reasons you listed but I dont understand why the Samsung S8 can't do better. 
Am I correct in assuming that your priorities lie in making ARCore available for all rather than pushing it to its limits on the latest high end phones. That would be understandable but also a bit sad for Google as a leader in inovative tech.

**Comment by burtonrider** [comment]
I'd like to add that we are not seeing this limit on iOS with ARKit and quick motions are perfectly fine. While I don't know how ARKit handles the "visual-inertial tracking" under the hood, I doubt you need to take extreme measures like 240fps to resolve this issue.

**Comment by chaosemer** [comment]
Could you capture a video recording of the camera image during this type of motion you expect to work? That'll help us diagnose the issue here.

"Quickly turn" is unclear to me; I don't know how quick you're moving.

**Comment by burtonrider** [comment]
Sent you an email! Thanks!
