### ISSUE TITLE
ARM64 libraries

### ISSUE THREAD

**Issue by MrSilverstone** [google-ar/arcore-unity-sdk#201]
IL2CPP on Unity 2018 can now generate arm64 code. Do you plan to release a 64 bit build of the libraries?

**Comment by pablisho** [comment]
Hi, thanks for the feature request.

**Comment by calebh** [comment]
64 bit support would be greatly appreciated. Any updates on this issue since May?

**Comment by boother** [comment]
Same question ...

**Comment by Teja337** [comment]
When can we expect 64bit build for the libraries??

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.

**Comment by falldeaf** [comment]
Everything seems to be working for 64bit except the libarcore_camera_utility.so

I'm getting a dll not found for this library in 64bit but not 32bit. I see the source comes with it and I'm trying to compile it into a 64bit library but I have no idea what I'm doing.

**Comment by germania** [comment]
@falldeaf since you managed to figure this out for yourself today and saved me a (further) headache, I'll link your SO post for anybody that gets this far into building ARCore apps for the Play Store:  https://stackoverflow.com/questions/58195077/how-do-i-build-the-arcore-camera-utility-shared-library-in-ndk-build
