### ISSUE TITLE
OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range 

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-unity-sdk#3]
Using the demo on a pixel, And the latest Unity beta.
PS: the demo works. But the monitors spams this error. Not sure, but I think every frame.

    08-29 14:11:40.564 13392-13407/? E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
                                           
    (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 368)

**Comment by nathanmartz** [comment]
Do you have any other plugins installed in that app or is it just a fresh project w/ the ARCore SDK installed, building HelloAR?

**Comment by GtoDair** [comment]
Assets/arcore-unity-sdk-master/Assets/GoogleARCore/SDK/Plugins/Scripts/Managers/AnchorManager.cs(27,36): error CS0234: The type or namespace name `XR' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?    

how to solve this problem

**Comment by iBicha** [comment]
No other plugin, running the project as is from the repo.

**Comment by nathanmartz** [comment]
@GtoDair, you are reporting a different error unrelated to this thread. Please file a separate issue.

@iBicha, I will follow up with someone from our team.

**Comment by seanbdoherty** [comment]
Note that the warning only shows up when the camera has information to process (if you cover the camera, the warning doesn't show up, only when the pointcloud/plane detection is active)

Also this message shows up periodically: 
 I tango   : vio_helper.cc:102 Not enough RANSAC inlier feature tracks for recovery.

**Comment by CarinaMclaneUWE** [comment]
Seconding this error, on Galaxy S8, latest Unity beta.

**Comment by nathanmartz** [comment]
We can reproduce this issue internally and are following up with Unity to get it resolved.

**Comment by markvitapoly** [comment]
Verified error still happening in Unity 2017.2.0b11, Pixel XL.

**Comment by lingllting** [comment]
I encountered the same issue.

**Comment by VadimTikhonyuk** [comment]
Same issue, Unity 2017.2.0 b9, Samsung S8

**Comment by iBicha** [comment]
Just stating the obvious, but of course the error is still happening, since there is only a single commit since the release.

**Comment by SafetyOrange** [comment]
Not sure if this is useful to anyone, but I noticed disabling/removing the PointCloud object stops the error from being thrown. This doesn't affect tracking, just removes visual feedback.

**Comment by chaosemer** [comment]
This should now be resolved in Developer Preview 2.

**Comment by spaul13** [comment]
I am also getting the error of Nexus 6P and using unity 5.6.4p4 and unity 2018.1.0b4.

**E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
(Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 388)**

can anyone tell me how to solve this or for exactly what reason, this is happening?

**Comment by chaosemer** [comment]
@spaul13, could you please elaborate on your issue?

I'm confused because neither the Nexus 6P nor Unity 5.6.4p4 are supported by the ARCore for Unity Preview SDK.

**Comment by spaul13** [comment]
Actually, I am getting this while playing a VR game implemented based on Unity. But hope you can help.

**02-07 14:44:33.059 11434-11492/? E/jni: CreateFBO 4096 2048 68
02-07 14:44:33.062 11434-11492/? E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
(Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 388)**

Alongwith these I am getting few OMX layer error,

_E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
 E/OMX-VDEC-1080P: Extension:OMX.google.android.index.describeColorAspects not implemented
 E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
 E/OMX-VDEC-1080P: Failed to call stream on OUTPUT due to HW_OVERLOAD
02-07 14:44:33.138 2724-11889/? E/OMX-VDEC-1080P: empty_this_buffer_proxy failure due to HW overload
02-07 14:44:33.138 2724-2724/? E/OMX-VDEC-1080P: Failed to set operating rate 64 fps (Invalid argument)
02-07 14:44:33.138 2724-2724/? E/OMXNodeInstance: setConfig(aa40117:qcom.decoder.avc, ConfigOperatingRate(0x6f800003)) ERROR: UnsupportedSetting(0x80001019)
02-07 14:44:33.139 2727-11887/? I/ACodec: codec does not support config operating rate (err -1010)
02-07 14:44:33.139 2724-11889/? E/OMX-VDEC-1080P: ERROR: Sending OMX_ErrorInsufficientResources to Client
02-07 14:44:33.140 2724-11889/? E/OMX-VDEC-1080P: Failed to qbuf to driver_

Can you please tell me why I am getting this kind of error and how to resolve this?

**Comment by chaosemer** [comment]
Sorry, I'm confused -- does the app you're running use ARCore?

**Comment by spaul13** [comment]
No. But I thought you can possibly help me on the same error, can also tell me the root cause of this. That's why I posted it here.

**Comment by chaosemer** [comment]
This can happen for many reasons. It basically means that native rendering code has changed the OpenGL state in a way that Unity is not prepared for. I can't help you further, sorry!

**Comment by Webee-JC** [comment]
**AndroidPlayer(samsung_SM-A715F@) Assertion failed: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range**

I can't really tell what's the effect on the app because the app still work perfectly.
