### ISSUE TITLE
Surface Detection Enhancement

### ISSUE THREAD

**Issue by denali95** [google-ar/arcore-unity-sdk#30]
Is there any way to adjust the threshold of what's considered a surface without breaking anything?  ARCore seems to be having a lot of trouble picking up surfaces in the environment around me which is well-lit.

**Comment by nathanmartz** [comment]
Not currently, no. These detectors are carefully tuned to produce the best results in a variety of surfaces. Note that we do require a reasonable amount of detail/texture. Pure flat color surfaces or very low contrast textures may not track well. Would you care to post a picture of the problematic space?

**Comment by denali95** [comment]
I've been trying it in a variety of environments (inside, outside, and been getting about consistent results throughout, with marginal improvements outdoors).  I was wondering, the camera on my arcore application doesn't seem to be in focus.  Is there a way I can adjust this?  Is it a Unity setting or mobile?

**Comment by eisenbruch** [comment]
Yea, it's not very crisp.

**Comment by fredsa** [comment]
The ARCore camera image uses a fixed camera focus, to aid with AR tracking. Moving the camera very close to surfaces and other objects may appear blurry while in AR mode.

**Comment by pshah123** [comment]
I've also been getting a considerable number of problems with surface detection. I haven't been able to get it to detect the carpet floor, my desk, a table, a book, or anything of that sort. The one thing I was able to detect is a metal rack (which is weird because there are just a few strips of metal lined up vertically). Seeing blue dots on some of the surfaces. Would be great to be able to adjust what is considered a surface!

**Comment by fredsa** [comment]
To detect a surface (with reasonable texture and with good lighting), make sure to move the phone through space (at least several inches), so that ARCore is able to see that surface from different angles and from different positions in the room.

If you rotate your phone around the camera sensor (so that the camera sensor stays the same position), ARCore won't have the stereo separation between images needed.

**Comment by pshah123** [comment]
I tried moving around but wasn't able to get much still. This is all I was able to get after ~15 minutes of trying to detect a surface:

![two surfaces](https://user-images.githubusercontent.com/6960204/35926557-586fb9e0-0c20-11e8-87ca-668e15b9cafa.png)

**Comment by n1n3b1t** [comment]
Have you tried cleaning lens? Especially if you are using s8 with fingerprint sensor near the camera.

**Comment by chaosemer** [comment]
We are constantly trying to make surface detection better. We've deployed a bunch of improvements since this was first filed.

If you have specific situations that are not having the plane detected, please report those along with a video.
