### ISSUE TITLE
Unity Instant Preview not working on Note 8 and S9

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [google-ar/arcore-unity-sdk#301]
Installed instant preview though Unity, installed arcore through play store. Hit play button in unity for brief second screen goes black on phone and goes back to default state displaying message Press Play in Unity editor to stream. In Unity itself the game screen is black and not showing camera feed.

Please note these issues are on note 8 and S9. 

unity version: 2018.1.7f1

**Comment by geeosp** [comment]
Neither S8 or S8+

**Comment by nick-strohm** [comment]
Same on S7

**Comment by small-potatoes** [comment]
Hi @Edgar-BlipparDev and @geeosp , can you please give me your device fingerprints (`adb shell getprop ro.build.fingerprint`)?  We have had some issues with exynos devices that should be addressed in the next release.

@nick-strohm , it looks your issue is separate and related to the augmented image database raw data being corrupted.  Please check the database and open a new issue if you are still having problems.

**Comment by geeosp** [comment]
Hi, thanks for addressing this issue.
This is all you need?
My device is a Galaxys8 SM-G950FD
This is what i get for ro.build.fingerprint
samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU3CRGH:user/release-keys

**Comment by small-potatoes** [comment]
Thanks for the additional information;  I believe this will be fixed by an instant preview update in the next release.

**Comment by pablisho** [comment]
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.
