### ISSUE TITLE
Regaining the recognized AugmentedImage and Plane when the tracking lost.

### ISSUE THREAD

**Issue by MustaphaGH** [google-ar/arcore-unity-sdk#323]
Hello,

We are creating the following experience using S8+ : 
1 - The user detect an image and create an Anchor as a parent to a 3D object.
2 - This 3D object will move far from it's Anchor position to a distance max of 100 Meters and the User (Camera) will follow it .

When the tracking is lost, we lose all the Anchors and the 3D objects attached to it. 
How can we regain the recognized AugmentedImage and Plane when the tracking is lost and the Camera/User is far from the original coordinates of the Image knowing that we can't tell the user to detect again the Image.

**Comment by pablisho** [comment]
Hi, when tracking is lost the Anchors go from Tracking state to paused state. If an anchor is Paused, then it's not useful for rendering content until it goes back to Tracking again. When tracking is recovered, ARCore will try to relocalize and Anchors will go back to Tracking when the environment is recognized. It's not necessary to look directly to the Anchor/AugImg again, but recognizing the environment is required.
I would suggest that you try to avoid environments without features (like completely white walls), that would help to not lose tracking. Let me know if this helps.

**Comment by MustaphaGH** [comment]
Thank you for the response,
Through some experiences , I observed this behavior of ARCore when the tracking plane is recovered . But I saw that even in that optimistic situation the Anchors attached to the AugmentedImages do not go back to Tracking unlike the Plane. 
Can we do something in the code to help ARCore recover these anchors ?

**Comment by fredsa** [comment]
@MustaphaGH In your case where you're having the user move far away (100m) from the originally detected Augmented Image, I think it no longer makes sense to try to use the image based anchor for the entire experience.

I suggest one of two options:

1. When the activation image is detected, use `Session.createAnchor()` or an anchor on the detected floor or ground plane, instead of an anchor on the detected image.
  * Which your use, depends on the environment and whether finding and maintaining tracking of the floor/ground for 100m is practical.

2. When the activation image is detected, start by using an anchor on the image. Then, when tracking of the original image is lost after the user begins walking, switch to a second (session or floor/ground based) anchor. If the user at any points returns to the original image, you could switch back to the original anchor. To make this second transition smooth, you can interpolate (lerp) between the two coordinate systems over a few frames.

Option 1 is easiest to implement, but does not provide good anchor of the spawned 3D object relative top the detected image. If that's okay for, use option 1.

Option 2 allows you to create the 3D object relative to the tracked image, but allows the user to walk far away and have a smooth experience while tracking. 

Hope that helps. If this does not solve your issue, feel free to reopen.

**Comment by SirApplejuicer** [comment]
Hey @fredsa Thanks for this solution. I just dont understand how and when to create the second anchor. do you have an example code for this?
