### ISSUE TITLE
Position data provided by ARCore

### ISSUE THREAD

**Issue by juanmajr93** [google-ar/arcore-unity-sdk#333]
Hi:

How could I get the whole position data from device using ARCore? I am interested to know gyroscope values in order to determine the first user orientation in my virtual world.

Thanks

**Comment by minnes09** [comment]
Hi, 
If you need only the orientation of the device, the Frame class has a Pose related to the ARCore device (and it´s the same of the camera). Otherwise you can use the rotation of the camera gameObject.
If you want the gyroscope information I think you need some Android class, try to look in the Unity documentation.

I hope I helped

**Comment by iBicha** [comment]
Just read it off the transform of the main camera, simplest way

**Comment by pablisho** [comment]
Hi, you can get camera pose from ARCore as [Frame.Pose](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Frame.cs#L45). Let me know if this helps, and feel free to comment if you have more questions.
