### ISSUE TITLE
Instant preview broken

### ISSUE THREAD

**Issue by ataylor09** [google-ar/arcore-unity-sdk#361]
Instant preview was previously working in my project. Now it seems to be broken. I get an error message like this:

`Trying to install Instant Preview APK but reference to InstantPreview.apk is broken. Couldn't find an asset with .meta file guid=cf7b10762fe921e40a18151a6c92a8a6.`

Any ideas how to fix this?

**Comment by pablisho** [comment]
Hi, thanks for the report. Did the error happened when upgrading the ARCore version? I would suggest that you delete the entire GoogleARCore folder and import it again. Let me know if this helps.

**Comment by fredsa** [comment]
Please reopen if you still have an issue after re-importing the SDK:

1. Quit/close Unity, so no files are locked
2. Delete `Assets/GoogleARCore` folder
3. Restart Unity
4. Import the latest ARCore SDK for Unity

When reopening the issue, please include the version of Unity and ARCore that you are using.

**Comment by EyezLee** [comment]
Hi @fredsa  @pablisho Instant Preview is **Broken again #742** 

**Version Data**

- Unity 2019.3.6f1, 2019.3.0f6, 2019.2.14f1

- Device info: Google Pixel 3, Android 10 (build number QQ3A.200705.002)

- ARCore version: 1.18.0

 https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.18.0

**How to Reproduce**

- Follow ARcore instruction: https://developers.google.com/ar/develop/unity/instant-preview

- Open HelloAR scene in  GoogleARCore

- Hit play in Unity editor

**Crash info**
![image](https://user-images.githubusercontent.com/18374192/89045643-cf95c980-d386-11ea-80c9-a4bd1ab317b7.png)

Is it because Instant Preview has not added **light estimation** and **depth function** judging by the console log?
