### ISSUE TITLE
White screen issue with non cloud anchor APP on ios 

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [google-ar/arcore-unity-sdk#384]
I followed this [tutrial here](https://developers.google.com/ar/develop/unity/quickstart-ios) to convert my plane detection app where i place furnitures to ios . But i am getting white screen and it doesn't ask for camera access. It works well on android though  . Does this issue #242  mean only cloud anchor is supported on IOS ? 
Is there a way to convert every arcore sample to ios ?

**Comment by small-potatoes** [comment]
Hi @FaiyazMdAbdul , we have no plans to convert every arcore sample to iOS since but only the ones involving ARCore features that work on both Android and iOS.  These types of examples are probably better suited for something like [ARFoundations](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@1.0/manual/index.html).
