### ISSUE TITLE
Sync the session of the host with the client : CloudAnchor

### ISSUE THREAD

**Issue by kushal98** [google-ar/arcore-unity-sdk#418]
Actually , I am using 2 arcore supported devices  for Cloud anchors example one to host a model and other to resolve it.But i can see as and when the object get resolved the phone which is resolving does'nt get synched with the hosts coordinates.So what am i supposed to do if i want to sync the coordinates of both the player.

**Comment by pablisho** [comment]
Hi, Cloud Anchors allow you to have the same physical location anchored in two different devices, but doesn't synchronize both devices' coordinates system.
You can synchronize the objects' relative pose to the anchor instead of the world pose, or you can use the Anchor pose to synchronize both coordinate spaces, but would require manual implementation on your side. Let me know if this helps.

**Comment by flankechen** [comment]
@pablisho world coordinate and cloud anchor rotation could not be synchronized, am I right? I place an object with anchor position and rotation, then rotate it to look at (0,0,0) in unity world coordinate; exactly the same on other devices, the object looks with a quite different rotation.


what you mean by "use the Anchor pose to synchronize both coordinate spaces, but would require manual implementation on your side". could you explained more on this? 


thanks

**Comment by kolboch** [comment]
@flankechen One idea is getting position from pose in both worlds, when computing difference you would be able to now the shift vector from one coordinate system to another. Then you are able to identify objects in both coordinates system by relevanat adding / substracting. Correct me if I am wrong :)

**Comment by tedruxpin** [comment]
This should be fixed in ARCore 1.6, please take a look at the new Cloud Anchor sample.
