### ISSUE TITLE
Instant preview doesn't work on V30 and S8

### ISSUE THREAD

**Issue by arisonu123** [google-ar/arcore-unity-sdk#452]
After upgrading from version 1.3 to version 1.5 the instant preview no longer works. It shows my phone's wallpaper for a second and then it goes back to the screen that says press play to connect to the Unity editor. I am using Unity version 2018.1.6f1.

**Comment by chaosemer** [comment]
This is fixed in 1.6.

**Comment by kolboch** [comment]
Please add LG G6 to the list :) It's not working since 1.4. I already recorded the video referenced in one of the issues: https://youtu.be/x589sd_QAh0 .
This issue should be reopened. I tested it with different versions of Unity, reinstalling both ARCore and InstantPreview app and it is still unresolved for my device.
