### ISSUE TITLE
cloude anchors 1.6

### ISSUE THREAD

**Issue by moishi** [google-ar/arcore-unity-sdk#469]
### SPECIFIC ISSUE ENCOUNTERED
i do not why, but in 1.6 version cloude anchors Can not identify identical surfaces, I tried different places, different devices, with wifi and without wifi.

### VERSIONS USED
- Unity:
- ARCore SDK for Unity: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Unity version
- ARCore SDK for Unity version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`
