### ISSUE TITLE
Big object is moving with camera, Unable to fix it's position

### ISSUE THREAD

**Issue by Talk2Sourabh** [google-ar/arcore-unity-sdk#492]
### VERSIONS USED
- Unity:
- ARCore SDK for Unity: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Unity version
- ARCore SDK for Unity version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`
