### ISSUE TITLE
Does plane detection increase accuracy of Augmented Image Tracking

### ISSUE THREAD

**Issue by alikanat001** [google-ar/arcore-unity-sdk#494]
I have an application for visualizing scan of a room and i am using an Augmented Images to calibrate my points to real world. I am not using plane detection in my application so it is optional for me. However, i have couple of questions regarding tracking accuracy because accuracy of my application solely depend on how accurate i can detect the center position and corners of the augmented image.

1. Does using plane detection increase accuracy of detecting an image position in an Augmented Image application.

2. Does it also affect accuracy of tracking and ARCore  environmental understanding. Because i tested my application with and without plane detection and it appears with plane detection my calibration changes over time because of ARCore environmental understanding and there is a shift in anchors. This does not happen that much without plane detection.

I thought of asking it here because it is directly related to concurrent odometry and mapping. Thanks for any help!

**Comment by fredsa** [comment]
Currently, Augmented Images are detected through features and are found on a plane, so it is helpful to scan the environment from different angles, so that ARCore can estimate depth of visible feature points and determine whether they are on a common plane.

Actual detection of a plane is not required, but the feature points of the detected image to need to exist on a plane. That is, bending/folding a piece of paper will cause image detection to stop working.

**Comment by manojghorela69** [comment]
Can you help me on how can I enable plane detection in augmented image app. I need to place the asset that is downloaded at later stage. So basically I need the functionality of both augment image  and HelloAr. I am currently working on Android.
