### ISSUE TITLE
Cloud Anchors Scene does not have option to resolve

### ISSUE THREAD

**Issue by RAUNAKKONDIBOYINA** [google-ar/arcore-unity-sdk#498]
### SPECIFIC ISSUE ENCOUNTERED
The sample scene of cloud anchors of the arcore version 1.6 seems to be underdeveloped. It doesn't have any option for resolving cloud anchors and as well the list of rooms is empty after reopening the app(after closing).

### VERSIONS USED
- Unity: 2018.3.3
- ARCore SDK for Unity:  1.6
- Device manufacturer, model, and O/S: pocof1
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1. I have only built the given sample scene of cloud anchors
 1.
 1.

**Comment by julianmateu** [comment]
Take a look to the [Quick Start Guide](https://developers.google.com/ar/develop/unity/cloud-anchors/quickstart-unity-android) and follow the steps there. The sample was changed so that there's no need for a "Resolve" button now. The sample uses [UNet](https://docs.unity3d.com/Manual/UNet.html); the host device will place an anchor and the other devices will resolve it when the Game Object is instantiated in the clients.

**Comment by marklinmao** [comment]
> Take a look to the [Quick Start Guide](https://developers.google.com/ar/develop/unity/cloud-anchors/quickstart-unity-android) and follow the steps there. The sample was changed so that there's no need for a "Resolve" button now. The sample uses [UNet](https://docs.unity3d.com/Manual/UNet.html); the host device will place an anchor and the other devices will resolve it when the Game Object is instantiated in the clients.

BUT, actually it doesn't resolve automatically at all. Just nothing happen.
