### ISSUE TITLE
How do you set Unity's XR Settings "ARCore Supported" in code?

### ISSUE THREAD

**Issue by Alexees** [google-ar/arcore-unity-sdk#58]

**Comment by chaosemer** [comment]
The ARCore Supported checkbox must be set at build time.

If you want to enable / disable ARCore connection at runtime, you can do this by managing the ARCore Device's lifecycle (destroy it when you want to stop ARCore tracking).

**Comment by Alexees** [comment]
@chaosemer it was not about runtime change. I just wanted to write an Editor script that sets everything up necessary for ARCore usage in Unity. But this one setting cannot be accessed

**Comment by chaosemer** [comment]
Got it. Unfortunately, this is not something we can fix in our plugin. You should [file a bug](https://unity3d.com/unity/qa/bug-reporting) with Unity. Please put the bug ID here so we can also keep track of it.

Thanks!

**Comment by rramprasad** [comment]
Hi,
I am adding UnityPlayer insided Android View. I am trying to use 2 different scenes for AR in Unity. 
Scene : 1 => Welcome screen to decide,device supports ARCore
Scene : 2 => If device supports ARCore, launch ARcore scene from my Android Activity
Scene : 3 => If device not supports ARCore,launch Vuforia scene from my Android Activity

So,for scene 1, I need to enable ARCore Supported in XR Settings
For scene 2,I need to enable Vuforia  Augmented Reality Supported in XR settings
Not able to enable both options.
So is it possible to set these options at runtime,before launching Unity Player from my Activity?

**Comment by chaosemer** [comment]
There is no way to set these at runtime. They must be set at build time.

**Comment by siekermantechnology** [comment]
In that case, what is your suggested alternative solution for AR apps in which it is required to have a fallback on devices which don't support ARCore?

One could be creating two separate apps, one for ARCore devices and one for non-ARCore devices, but that is definitely not a desired solution.

Note also that with ARKit on iOS this is not a problem at all. Using the ARKit Unity plugin it's no issue to combine that with Vuforia and at runtime enable the one or the other, depending on the iPhone/iPad model and iOS version. It would be great to have such an option for ARCore as well.

**Comment by chaosemer** [comment]
Right now we don't have a solution for that use case. The best solution is like you said, building two apks.

**Comment by siekermantechnology** [comment]
To my surprise, it looks like combining Vuforia and ARCore actually works. Although as soon as you enable them both in the Player Settings => XR Settings, Unity gives a message "Both ARCore and Vuforia XR Device support cannot be selected at the same time. Please select only one XR Device that will manage the Android device", it does not actually stop you from making a build with those settings both enabled. 

The way I've set it up now is that game objects for both AR modes are inactive in the hierarchy. When the app starts, it does some checks to determine ARCore support. If ARCore is not supported, it enables the Vuforia game objects, otherwise it enables the ARCore game objects.

On devices with Android API level lower than 24 (7.0), I default to Vuforia. On 7.0 or higher, I use the ARCore Session class to check for support. If for any reason support is not available, either because the device doesn't support it or because for instance the user denies the request to install the ARCore service APK, I fall back to Vuforia.

Testing so far looks like it works like a charm, very similar to how we're doing this with ARKit. You guys might as well disable that error message in the Player Settings, because it seems to be kind of pointless.

**Comment by romanunit** [comment]
Siekerman Technology, can you show how you resolve problem with check if android support ARCore?

**Comment by Alexees** [comment]
I filed a bug report on Unity Case 1022359

**Comment by hellaeon** [comment]
@Alexees 

`using UnityEditor;
using UnityEngine;
using GoogleARCoreInternal;

public class ARCoreBuilder : MonoBehaviour
{
    private const string k_MenuName = "Edit/Project Settings/ARCore/ARCore Required";

    [MenuItem("Build/Build Android ARCore")]
    public static void AndroidWithARCoreBuild()
    {
        BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions();

        // ... build player options stuff ...

        PlayerSettings.Android.minSdkVersion = AndroidSdkVersions.AndroidApiLevel24;
        SetAndroidTangoBool(true);
        
        // unsure if I need to worry about the Edit->Project Settings->AR Core option
        ARCoreProjectSettings.Instance.IsARCoreRequired = true;
        ARCoreProjectSettings.Instance.Save();
        Menu.SetChecked(k_MenuName, ARCoreProjectSettings.Instance.IsARCoreRequired);
        BuildPipeline.BuildPlayer(buildPlayerOptions);
    }

    [MenuItem("Build/Build Android without ARCore")]
    public static void AndroidWithoutARCoreBuild()
    {
        BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions();

        // ... build player options stuff ...

        PlayerSettings.Android.minSdkVersion = AndroidSdkVersions.AndroidApiLevel23;
        SetAndroidTangoBool(false);

        // unsure if I need to worry about the Edit->Project Settings->AR Core option
        ARCoreProjectSettings.Instance.IsARCoreRequired = false;
        ARCoreProjectSettings.Instance.Save();
        Menu.SetChecked(k_MenuName, ARCoreProjectSettings.Instance.IsARCoreRequired);
        BuildPipeline.BuildPlayer(buildPlayerOptions);
    }

    public static void SetAndroidTangoBool(bool b)
    {
        var ps = Resources.FindObjectsOfTypeAll<PlayerSettings>();
        var so = new SerializedObject(ps);

        var sp = so.FindProperty("AndroidEnableTango");

        sp.boolValue = b;
        so.ApplyModifiedProperties();
    }

}`

**Comment by Alexees** [comment]
@hellaeon thanks for the code snipped :)
