### ISSUE TITLE
Instant preview support on Linux builds

### ISSUE THREAD

**Issue by hetsch** [google-ar/arcore-unity-sdk#694]
I'm currently using Unity in Linux and was fighting hard to get instant preview working, until I found this thread, explaining that Instant Preview is not working on Linux (#164). The workarounds in the issue don't work for me anymore. 

Would it be possible that you add a information in https://developers.google.com/ar/develop/unity/instant-preview that Linux builds are not supported? This would have saved me some time and might help other people in the future.

As described in #164, the builds on Linux are breaking again because of a missing dll. Do you have any suggestions or workaround to overcome this problem?

And my last question would be, if you will ever support Instant Preview on Linux if it is fully supported by Unity themselves (https://blogs.unity3d.com/2019/05/30/announcing-the-unity-editor-for-linux/)?

### VERSIONS USED
- Unity: 2019.3.1f1
- ARCore SDK for Unity: 1.5.0 
- Device manufacturer, model, and O/S: Ubuntu 19.10

**Comment by Gjohnson6** [comment]
Hey hetsch,

Instant Preview does not support running on Linux and we currently don't have plans to add support for running on Linux. You should still be able to build applications using the Unity Editor on Linux using the build menu, although running using the game preview in Editor won't work because it depends on Instant Preview.
