### ISSUE TITLE
Null Reference Exception if tap on GameObject not meant to be manipulated

### ISSUE THREAD

**Issue by jjaslow** [google-ar/arcore-unity-sdk#733]
### SPECIFIC ISSUE ENCOUNTERED

DragGesture.CS and TapGesture.CS (maybe other gestures also) assign the TargetObject to the GameObject that is manipulated in the OnStart method. However this is done through gameObject.GetComponentInParent<Manipulator>().gameObject

If a  GameObject not intended to be manipulated is tapped then the Manipulator component is not found causing a Null Ref Exception. 

I added a null check for the Manipulator to address this.

### VERSIONS USED
- Unity: 2019.3.6fa
- ARCore SDK for Unity: 1.15.0
- Device manufacturer, model, and O/S: Galaxy S10+

**Comment by rsfuller** [comment]
Thanks for the report. 

The manipulator component you refer to appears to be the [UIElements.Manipulator](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/Experimental.UIElements.Manipulator.html). So, this appears to be a Unity UI issue instead of an ARCore one.

I am closing this issue for now, but if there is an interaction via the ARCore SDK that is causing a NPE, please let us know how to reproduce it specifically (with what sample app you are using if any) and reopen the issue. I would recommend upgrading to the latest version of the ARCore SDK for Unity (currently 1.18.0).
