### ISSUE TITLE
FixedUpdate function of MonoBehaviour is called strange

### ISSUE THREAD

**Issue by deadmarston** [google-ar/arcore-unity-sdk#75]
0.03073645  15:3:59 526
0.0321269  15:3:59 527
0.05752754  15:3:59 553
0.09203053  15:3:59 587
0.09224319  15:3:59 588
0.1255956  15:3:59 621
0.1258216  15:3:59 621
0.1574659  15:3:59 653
0.1905837  15:3:59 686
0.1908412  15:3:59 686
I tried to use FixedUpdate to get some arcore information, then I found that the time between each call of fixedupdate is strange. The info up is Time.realtimeSinceStartup and System.DateTime.Now infor in each fixedupdate call. I set the fix time 0.02s in Unity, but the actual data I got is strange, sometimes the delta time is less than 0.01s. 
My Unity Version is 2017.3.0f3, and I didn't find it happen when I use 2017.3 to build other non-arcore apks.

**Comment by chaosemer** [comment]
This sounds expected to me -- FixedUpdate only make guarantees about the value of Time.DeltaTime and that it will get called correctly over time.

Your change of behavior sounds like it is happening because by default ARCore tries to match the camera framerate instead of the display framerate. You can control this in the settings on device.

(I'm closing this because it does not sound like a bug.)
