### ISSUE TITLE
How to control an animation state using ui button in unity arcore?

### ISSUE THREAD

**Issue by sajidsrt** [google-ar/arcore-unity-sdk#90]
I want to control an animation state through a ui button in unity arcore. I had tried these steps for controlling the "pose" state through the button but no result.

![catanim](https://user-images.githubusercontent.com/22423463/35636920-87502be4-06aa-11e8-9914-f5a312714644.PNG)
![catanim2](https://user-images.githubusercontent.com/22423463/35636926-87cddbc0-06aa-11e8-8602-a06d19cf2ae5.PNG)
![catanim3](https://user-images.githubusercontent.com/22423463/35636937-8e6199f4-06aa-11e8-90dd-ae06830bf538.PNG)
![catanim4](https://user-images.githubusercontent.com/22423463/35636966-9ff4a5ee-06aa-11e8-837b-8135f080d03c.PNG)
![catanim5](https://user-images.githubusercontent.com/22423463/35636968-a06adaca-06aa-11e8-9504-866b3c994fcc.PNG)

**Comment by chaosemer** [comment]
There's nothing here that's ARCore specific. I suggest asking on the [Unity forums](https://forum.unity.com/), there's a lot of experienced people there!

**Comment by Storm-Develop** [comment]
@chaosemer  It's actually related to Google ARCore.
The problem that GoogleAR Controller creates a clone of the 3d object. So that the one which is displayed on the detected surface is the clone of the original. 
https://github.com/google-ar/arcore-unity-sdk/blob/c8b21aedaa2c9e5372124b3cd430955fb137263f/Assets/GoogleARCore/Examples/HelloAR/Scripts/HelloARController.cs#L136
Which means if your Animations are referenced to the original copy which it is based on images @sajidsrt provided. Than you **will not see** the effect of animations in the AR app. But will see in the Unity editor.

The solution would be is to pass the 3d Model copy to your code.
`     yourScript.saveAndyCloned(andyObject);`
And in yourScript extract the Animations by doingsomething like this:
` private Animator[] AnimatorsGameObjectlist;`
  ` public void saveAndyCloned(GameObject input)`
` {`
      `ATVCloned = input;`
    `AnimatorsGameObjectlist = input.GetComponentsInChildren<Animator>();`
    `}`
It's not only with Animations but also with any gameobject references which are child of the 3dModel which you deploy using GoogleARcore.
I would recommend make it clear to developers since it's easy to miss when develop the code. And than you have the routine of investigation where everything works in Unity but not after exporting to Android or IOS. 
@sajidsrt Sorry it may be too late but I hope it helps in the future projects.

**Comment by chaosemer** [comment]
Thanks for the additional info.

You are right that if an Animation references a specific object in the scene, HelloAR will clone it. Our example assumes that AndyObjectPrefab in HelloARController is a prefab and not an object in the scene. Please don't feel obligated to use any of the example code directly, we expect that you'll need to clone the scripts and further customize them to suit your design.

If you have suggestions in what we can do to make the prefab assumption clearer, we'd love to know.
