### ISSUE TITLE
Enable virtual reality support causes an error during project build

### ISSUE THREAD

**Issue by jeremy-giles** [google-ar/arcore-unity-sdk#94]
Unity 2017.3.0p2 Personal (64bit) - OpenGL 4.1
arcore-unity-sdk-prebiew2
MacOS

I created a simple Unity Android project with a plan and an ARCode Device (Camera) -> Build OK
I update this latter with like this :
 - Player Settings -> Android
 - XR Settings 
 - Enabled Virtual Reality Supported
 - Add Cardboard SDKs option (without download/upload/import SDK)
 - Build

I've a build error :
Unable to convert classes into dex format. See the Console for details.

Details :
CommandInvokationFailure: Unable to convert classes into dex format.
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/name/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/aidl/BaseProxy;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/aidl/BaseStub;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/aidl/Codecs;
3 errors; aborting
]
stdout[
ignored resource /Users/name/ARCoreS8/Temp/StagingArea/android-libraries/arcore_client/libs/./armeabi-v7a/libarcore_sdk.so
processing archive /Users/name/ARCoreS8/Temp/StagingArea/android-libraries/arcore_client/libs/./classes.jar...
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/aidl/
processing com/google/android/aidl/BaseProxy.class...
processing com/google/android/aidl/BaseStub.class...
....

**Comment by WazzaMo** [comment]
I've seen errors like that when i install Java 9.
It breaks the build system just having it in the system PATH from memory.

**Comment by cgydev** [comment]
Based on what I learned while trying the same is that **BaseProxy**, **BaseStub** & **Codes** from ARCore SDK are clashing with the same once in VRSDK.
I assume this will be fixed in later builds but as a temporary fix do the following,
1. Locate file **arcore_client.aar** in **Assets/GoogleARCore/SDK/Plugins**
2. Using **7Zip** open the file.
3. Open **classes.jar** and go to location **com\google\android\aidl**
4. Delete the 3 classes in that location (_BaseProxy.class, BaseStub.class & Codes.class_)
5. Save the Archive, and now ARCore should work with GoogleVR.

Hope this helps.

**Note:** Once the modification is done to the AAR file, within the same project building standalone AR app _(without VR)_ becomes difficult.

**PS** Fix based on Solution at [Link](https://github.com/googlevr/gvr-android-sdk/issues/518) suggested by [Priansh](https://www.youtube.com/user/DarkhoodtheArchmage)

**Comment by chaosemer** [comment]
This was also reported at https://github.com/google-ar/arcore-android-sdk/issues/180. It is fixed in ARCore 1.0.
